profiles:
  brave_search:
    target-env:
      BRAVE_API_KEY: "file:~/.secrets/BRAVE_API_KEY"
  github:
    target-env:
      GITHUB_PERSONAL_ACCESS_TOKEN: "file:~/.secrets/GITHUB_PERSONAL_ACCESS_TOKEN"
