# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.19.2
    hooks:
      - id: gitleaks
        entry: gitleaks protect -v --redact --staged --config .gitleaks.toml
        require_serial: true
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
    - id: check-json5
  - repo: local
    hooks:
      - id: aicommit2
        name: AI Commit Message Generator
        entry: aicommit2 --pre-commit
        language: node
        stages: [prepare-commit-msg]
        always_run: true
